name: build

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master
  # release:
  #   types:
  #     - released

jobs:
  build:
    defaults:
      run:
        shell: bash
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [latest]
        architecture: [x64]
    name: build on ${{ matrix.os }}.${{ matrix.architecture }} node v${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
      - run: |
          cd build
          npm i --ignore-scripts
          npm run build
